#!/usr/bin/env perl
use strict;
use warnings;

use SDL;
use SDLx::Surface;
use SDL::Video;
use SDL::Image;

for(grep { !/\/C(?!.*\/)/ and !/^C(?!.*\/)/ } glob "$ARGV[0]*.bmp") {
	my $surf = SDLx::Surface->new(surface => SDL::Image::load($_));
	my $crop = SDLx::Surface->new(w => $ARGV[3], h => $ARGV[4], d => $surf->format->BitsPerPixel);
	
	$surf->blit($crop, [ @ARGV[1..4] ], undef);
	
	s/\/(?!.*\/)/\/C/ or s/^/C/;
	SDL::Video::save_BMP($crop, $_) and die "Could not save bmp: " . SDL::get_error;
}
