#!/usr/bin/env perl
use strict;
use warnings;

use SDL;
use SDLx::Surface;
use SDL::Video;
use SDL::Image;

my @file = grep !/(?:^|\/)Tiled\.bmp$/, glob "img/$ARGV[0]*.bmp";
my $first = 1;
my ($strip, $h);
for(0..$#file) {
	my $surf = SDLx::Surface->new(surface => SDL::Image::load($file[$_]));
	if($first) {
		$h = $surf->h;
		$strip = SDLx::Surface->new(w => $surf->w, h => $h * @file, d => $surf->format->BitsPerPixel);
		$first = 0;
	}
	$surf->blit($strip, undef, [0, $_ * $h]);
}

$_ = $ARGV[0];
s/\/[^\/]+$//;
SDL::Video::save_BMP($strip, "$_/Tiled.bmp") and die "Could not save bmp: " . SDL::get_error;
