#!/usr/bin/env perl
use strict;
use warnings;

use SDL;
use SDLx::Surface;
use SDL::Video;
use SDL::Image;

my @file = glob "img/$ARGV[0]*.bmp";
my $length = 0;
for(@file) {
	if(/(\d+)(?!.*\d)/) {
		$length = length $1 if length $1 > $length;
	}
	else {
		$_ = undef;
	}
}
for(grep defined, @file) {
	my $old = $_;
	s/(\d+)(?!.*\d)/
		sprintf "%0${length}d", $1
	/e;
	rename $old, $_ if $old ne $_;
	SDL::Video::save_BMP(SDL::Image::load($_), $_) and die "Could not save bmp: " . SDL::get_error;
}
